"""Run the G-code validator against known-good and unsafe fixtures."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from validate_gcode import validate  # noqa: E402
from ensure_m99123_first import (  # noqa: E402
    FEATURE_FLOW_MARKER,
    FIRST_USE_UNRETRACT,
    apply_ideamaker_feature_flow,
    convert_m204_line,
    copy_slicer_height_after_layer,
    emit_raisetouch_times,
    fill_skipped_object_first_layers,
    inject_bounding_box,
    insert_next_tool_preheat,
    keep_idle_nozzle_standby,
    parse_hms,
    prime_first_toolchange,
    rewrite,
    xy_then_z_after_purge,
)

FIXTURES = ROOT / "tests" / "fixtures"


class GcodeSafetyTests(unittest.TestCase):
    def test_ideamaker_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_left_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_unsafe_fixture_fails(self) -> None:
        errors = validate(FIXTURES / "unsafe_commands.gcode")
        joined = "\n".join(errors)
        self.assertTrue(any("G29" in e for e in errors), joined)
        self.assertTrue(any("M92" in e for e in errors), joined)
        self.assertTrue(any("M600" in e for e in errors), joined)

    def test_non_gcode_line_after_m1001_fails(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        poisoned = src.replace("M1001\n", "M1001\nFilament Name: [Raise3D] PLA\n", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "garbage.gcode"
            path.write_text(poisoned, encoding="utf-8")
            errors = validate(path)
        joined = "\n".join(errors)
        self.assertTrue(any("not G-code" in e and "Filament Name" in e for e in errors), joined)

    def test_dual_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "dual_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_ideamaker_right_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_right_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))

    def test_ideamaker_dual_start_end_passes(self) -> None:
        errors = validate(FIXTURES / "ideamaker_dual_start_end.gcode")
        self.assertEqual(errors, [], msg="\n".join(errors))


    def test_start_only_is_not_a_complete_job(self) -> None:
        errors = validate(FIXTURES / "ideamaker_left_start.gcode")
        self.assertTrue(any("M1002" in e for e in errors))
        self.assertTrue(any("shutdown" in e.lower() or "M104 S0" in e or "M84" in e for e in errors))

    def test_ensure_m99123_first_moves_prusaslicer_preamble(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        self.assertTrue(src.startswith("M99123 "))
        preamble = (
            "; generated by PrusaSlicer 2.9.6 on 2026-08-25 at 16:06:58 UTC\n"
            "\n"
            "; thumbnail begin 32x32 12\n"
            "; AAAA\n"
            "; thumbnail end\n"
            "\n"
            ";TYPE:Custom\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "slice.gcode"
            path.write_text(preamble + src, encoding="utf-8", newline="\n")
            errors_before = validate(path)
            self.assertTrue(any("M99123" in e and "line 1" in e for e in errors_before))
            self.assertEqual(rewrite(path), "moved")
            out = path.read_text(encoding="utf-8")
            self.assertTrue(out.startswith("M99123 "))
            self.assertIn("; generated by PrusaSlicer", out)
            self.assertEqual(rewrite(path), "already")
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_ensure_m99123_first_missing_header(self) -> None:
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "nohs.gcode"
            path.write_text("G28 X0 Y0\n", encoding="utf-8")
            self.assertEqual(rewrite(path), "missing")

    def test_convert_m204_matches_ideamaker_set_velocity_limit(self) -> None:
        self.assertEqual(convert_m204_line("M204 S2000"), "SET_VELOCITY_LIMIT ACCEL=2000.00")
        self.assertEqual(convert_m204_line("M204 S5000"), "SET_VELOCITY_LIMIT ACCEL=5000.00")
        self.assertEqual(
            convert_m204_line("M204 S2500 ; adjust acceleration"),
            "SET_VELOCITY_LIMIT ACCEL=2500.00; adjust acceleration",
        )
        self.assertEqual(convert_m204_line("G1 X10"), "G1 X10")

    def test_rewrite_converts_m204(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "m204.gcode"
            path.write_text(src.replace("G1 X110 E5", "M204 S2000\nG1 X110 E5", 1), encoding="utf-8")
            self.assertTrue(any("M204" in e for e in validate(path)))
            self.assertEqual(rewrite(path), "already")
            out = path.read_text(encoding="utf-8")
            self.assertIn("SET_VELOCITY_LIMIT ACCEL=2000.00", out)
            self.assertNotIn("M204", out)
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_next_tool_preheat_inserts_m104_before_swap_wait(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        out, n = insert_next_tool_preheat(src)
        self.assertEqual(n, 0)
        self.assertEqual(out, src)

        g1_idx = next(i for i, line in enumerate(src) if line.startswith("G1 X100"))
        padded = src[: g1_idx + 1] + ["G1 X101 E0.1"] * 500 + src[g1_idx + 1 :]
        out, n = insert_next_tool_preheat(padded)
        self.assertEqual(n, 1)
        pre = [line for line in out if "next-tool preheat" in line]
        self.assertEqual(len(pre), 1)
        self.assertIn("M104 T1 S205", pre[0])
        m1001 = next(i for i, line in enumerate(out) if line.strip() == "M1001")
        pre_i = next(i for i, line in enumerate(out) if "next-tool preheat" in line)
        wait_i = next(
            i for i, line in enumerate(out) if i > m1001 and line.startswith("M109 T1")
        )
        self.assertLess(pre_i, wait_i)
        self.assertGreater(pre_i, m1001)
        out2, n2 = insert_next_tool_preheat(out)
        self.assertEqual(n2, 0)

    def test_next_tool_preheat_uses_m73_remaining_seconds(self) -> None:
        src = ["T0", "M1001", "M73 P0 R10"]
        src += ["G1 X1 E0.01"] * 80
        src += ["M73 P50 R1.0"]
        src += ["G1 X2 E0.01"] * 80
        src += ["M73 P90 R0.5", "M109 T1 S205", "T1", "M1002"]
        out, n = insert_next_tool_preheat(src)
        self.assertEqual(n, 1)
        pre_i = next(i for i, line in enumerate(out) if "next-tool preheat" in line)
        self.assertEqual(out[pre_i + 1], "M73 P50 R1.0")
        wait_i = next(i for i, line in enumerate(out) if line.startswith("M109 T1"))
        self.assertLess(pre_i, wait_i)
        self.assertGreaterEqual(wait_i - pre_i, 50)
        out2, n2 = insert_next_tool_preheat(out)
        self.assertEqual(n2, 0)

    def test_first_use_unretract_after_start_e11(self) -> None:
        lines = [
            "; generated by PrusaSlicer 2.9.6",
            "T0",
            "G1 F200 E-11.00",
            "M1001",
            "G1 X100 E1",
            "T1",
            "G1 X120 E8",
            "T1",
            "G1 X121 E8",
            "M1002",
        ]
        out, n = prime_first_toolchange(lines)
        self.assertEqual(n, 1)
        t1 = out.index("T1")
        self.assertEqual(out[t1 + 1], FIRST_USE_UNRETRACT)
        self.assertEqual(out.count(FIRST_USE_UNRETRACT), 1)
        out2, n2 = prime_first_toolchange(out)
        self.assertEqual(n2, 0)

    def test_first_use_unretract_skips_ideamaker(self) -> None:
        lines = ["T0", "M1001", "T1", "M1002"]
        out, n = prime_first_toolchange(lines)
        self.assertEqual(n, 0)
        self.assertEqual(out, lines)

    def test_idle_layer_temp_dropped_for_parked_tool(self) -> None:
        lines = [
            "; generated by PrusaSlicer 2.9.6",
            "T0",
            "M1001",
            "M104 T1 S180",
            ";LAYER:1",
            "M104 S250 T0 ; set temperature",
            "M104 S250 T1 ; set temperature",
            "G1 X100 E1",
            "M104 T1 S250 ; next-tool preheat (ideaMaker Multicolor)",
            "M1002",
        ]
        out, n = keep_idle_nozzle_standby(lines)
        self.assertEqual(n, 1)
        self.assertIn("M104 S250 T0 ; set temperature", out)
        self.assertNotIn("M104 S250 T1 ; set temperature", out)
        self.assertIn("M104 T1 S250 ; next-tool preheat (ideaMaker Multicolor)", out)
        self.assertIn("M104 T1 S180", out)

    def test_t1_left_keepout_after_m1001_fails(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        poisoned = src.replace("G1 X120 Y100 E8", "G1 X10 Y100 E8", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "t1_keepout.gcode"
            path.write_text(poisoned, encoding="utf-8")
            errors = validate(path)
        joined = "\n".join(errors)
        self.assertTrue(any("T1" in e and "keep-out" in e for e in errors), joined)

    def test_t0_left_of_keepout_after_m1001_is_ok(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        t0_left = src.replace("G1 X100 Y100 Z0.3 F900", "G1 X10 Y100 Z0.3 F900", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "t0_left.gcode"
            path.write_text(t0_left, encoding="utf-8")
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_parse_hms(self) -> None:
        self.assertEqual(parse_hms("3h 16m 9s"), 3 * 3600 + 16 * 60 + 9)
        self.assertEqual(parse_hms("45m 12s"), 45 * 60 + 12)
        self.assertEqual(parse_hms("30s"), 30)

    def test_emit_raisetouch_times_from_m73_and_stats(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        layer0 = next(i for i, line in enumerate(src) if line == ";LAYER:0")
        padded = (
            src[:layer0]
            + [
                "M73 P0 R193",
                ";LAYER_CHANGE",
                ";Z:0.2",
                ";HEIGHT:0.2",
                ";LAYER:0",
                "G1 X100 Y100 Z0.2 F900",
                "M73 P50 R96",
                ";LAYER_CHANGE",
                ";Z:0.4",
                ";HEIGHT:0.2",
                ";LAYER:1",
            ]
            + src[layer0 + 1 :]
            + [
                "; filament used [mm] = 20436.15, 0.00",
                "; filament cost = 1.22, 0.00",
                "; estimated printing time (normal mode) = 3h 13m 0s",
            ]
        )
        out, n = emit_raisetouch_times(padded)
        self.assertGreaterEqual(n, 3)
        self.assertNotIn("M73 P0 R193", out)
        i0 = out.index(";LAYER:0")
        self.assertEqual(out[i0 - 2 : i0], [";PRINTING_TIME: 0", ";REMAINING_TIME: 11580"])
        i1 = out.index(";LAYER:1")
        self.assertEqual(out[i1 - 2 : i1], [";PRINTING_TIME: 5820", ";REMAINING_TIME: 5760"])
        lc = out.index(";LAYER_CHANGE")
        self.assertFalse(out[lc - 1].startswith(";REMAINING_TIME:"))
        fw = next(i for i, line in enumerate(out) if line.startswith(";Firmware:"))
        self.assertEqual(out[fw + 1], ";Print Time: 11580")
        self.assertIn(";Material#1 Used: 20436.2", out)
        self.assertIn(";Material#1 Cost: 1.22", out)
        self.assertTrue(any(line.startswith(";Print Time:") for line in out[-10:]))
        out2, n2 = emit_raisetouch_times(out)
        self.assertEqual(n2, 0)

    def test_emit_raisetouch_times_layer0_uses_footer_seconds(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        layer0 = next(i for i, line in enumerate(src) if line == ";LAYER:0")
        padded = (
            src[:layer0]
            + [
                "M73 P0 R193",
                ";LAYER_CHANGE",
                ";Z:0.2",
                ";HEIGHT:0.2",
                ";LAYER:0",
            ]
            + src[layer0 + 1 :]
            + ["; estimated printing time (normal mode) = 3h 16m 9s"]
        )
        out, _n = emit_raisetouch_times(padded)
        i0 = out.index(";LAYER:0")
        self.assertEqual(out[i0 - 2 : i0], [";PRINTING_TIME: 0", ";REMAINING_TIME: 11769"])

    def test_copy_slicer_height_after_layer_not_custom_gcode(self) -> None:
        src = [
            ";LAYER_CHANGE",
            ";Z:0.2",
            ";HEIGHT:0.2",
            ";PRINTING_TIME: 0",
            ";REMAINING_TIME: 3600",
            ";LAYER:0",
            ";Z:0.2",
            "G92 E0",
        ]
        out, n = copy_slicer_height_after_layer(src)
        self.assertEqual(n, 1)
        i0 = out.index(";LAYER:0")
        self.assertEqual(out[i0 : i0 + 3], [";LAYER:0", ";Z:0.2", ";HEIGHT:0.2"])
        self.assertEqual(out.count(";HEIGHT:0.2"), 2)
        out2, n2 = copy_slicer_height_after_layer(out)
        self.assertEqual(n2, 0)
        self.assertEqual(out2, out)

    def test_emit_raisetouch_times_interpolates_without_m73(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        layer0 = next(i for i, line in enumerate(src) if line == ";LAYER:0")
        padded = (
            src[:layer0]
            + [";LAYER_CHANGE", ";Z:0.2", ";LAYER:0", ";LAYER_CHANGE", ";Z:0.4", ";LAYER:2"]
            + src[layer0 + 1 :]
            + ["; estimated printing time (normal mode) = 1h 0m 0s"]
        )
        out, n = emit_raisetouch_times(padded)
        self.assertGreater(n, 0)
        i0 = out.index(";LAYER:0")
        self.assertEqual(out[i0 - 2 : i0], [";PRINTING_TIME: 0", ";REMAINING_TIME: 3600"])
        i2 = out.index(";LAYER:2")
        self.assertEqual(out[i2 - 2 : i2], [";PRINTING_TIME: 3600", ";REMAINING_TIME: 0"])

    def test_inject_bounding_box_from_layer_z(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        out, n = inject_bounding_box(src)
        self.assertEqual(n, 1)
        self.assertIn(";Bounding Box: 100.000 120.000 100.000 100.000 0.000 0.300", out)
        out2, n2 = inject_bounding_box(out)
        self.assertEqual(n2, 0)

    def test_inject_bounding_box_rewrites_xmin_ymin_order(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        fw = next(i for i, line in enumerate(src) if line.startswith(";Firmware:"))
        wrong = (
            src[: fw + 1]
            + [";Bounding Box: 97.278 60.497 206.878 195.457 0.000 41.900"]
            + src[fw + 1 :]
        )
        out, n = inject_bounding_box(wrong)
        self.assertEqual(n, 1)
        self.assertIn(";Bounding Box: 100.000 120.000 100.000 100.000 0.000 0.300", out)
        self.assertNotIn(";Bounding Box: 97.278 60.497 206.878 195.457 0.000 41.900", out)

    def test_emit_raisetouch_times_synthesizes_layer0_after_m1001(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        i0 = src.index(";LAYER:0")
        padded = (
            src[:i0]
            + [";LAYER_CHANGE", ";Z:0.3", ";HEIGHT:0.3", ";LAYER:1"]
            + src[i0 + 2 :]
            + ["; estimated printing time (normal mode) = 3h 1m 41s"]
        )
        self.assertFalse(any(line.strip() == ";LAYER:0" for line in padded))
        out, n = emit_raisetouch_times(padded)
        self.assertGreater(n, 0)
        m1001 = next(i for i, line in enumerate(out) if line.strip() == "M1001")
        self.assertEqual(
            out[m1001 + 1 : m1001 + 6],
            [
                ";PRINTING_TIME: 0",
                ";REMAINING_TIME: 10901",
                ";LAYER:0",
                ";Z:0.3",
                ";HEIGHT:0.3",
            ],
        )
        i1 = out.index(";LAYER:1")
        self.assertTrue(out[i1 - 2].startswith(";PRINTING_TIME:"))
        self.assertTrue(out[i1 - 1].startswith(";REMAINING_TIME:"))
        out2, n2 = emit_raisetouch_times(out)
        self.assertEqual(n2, 0)
        self.assertEqual(out2.count(";LAYER:0"), 1)

    def test_rewrite_is_idempotent_after_raisetouch_times(self) -> None:
        import tempfile

        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "times.gcode"
            path.write_text(
                src
                + "\n; estimated printing time (normal mode) = 1h 0m 0s\n"
                + "M73 P0 R60\n",
                encoding="utf-8",
            )
            self.assertEqual(rewrite(path), "already")
            first = path.read_text(encoding="utf-8")
            self.assertIn(";REMAINING_TIME: 3600", first)
            self.assertNotIn("M73 P0 R60", first)
            self.assertEqual(rewrite(path), "already")
            self.assertEqual(path.read_text(encoding="utf-8"), first)
            self.assertEqual(validate(path), [], msg="\n".join(validate(path)))

    def test_xy_then_z_after_purge_matches_ideamaker(self) -> None:
        src = [
            "M99123 hdr",
            ";Firmware: Klipper",
            "G1 Z15.0 F300",
            "G1 F140 E29",
            "M1001",
            "G1 E-1.5 F2400",
            "G1 Z.3 F300",
            "G1 X140.549 Y181.524 F9000",
            "G1 Z.3 F300",
            "G1 E1.5 F1500",
            "G1 X141 E0.01",
            "M1002",
        ]
        out, n = xy_then_z_after_purge(src)
        self.assertEqual(n, 1)
        m1001 = out.index("M1001")
        xy_i = next(i for i, line in enumerate(out) if "X140.549" in line)
        z_i = next(i for i, line in enumerate(out) if line.startswith("G0 F300 Z"))
        self.assertLess(m1001, xy_i)
        self.assertLess(xy_i, z_i)
        self.assertEqual(out[xy_i], "G1 X140.549 Y181.524 F9000")
        self.assertEqual(out[z_i], "G0 F300 Z.3")
        self.assertEqual(out.count("G1 Z.3 F300"), 0)
        out2, n2 = xy_then_z_after_purge(out)
        self.assertEqual(n2, 0)
        self.assertEqual(out2, out)

    def test_xy_then_z_splits_combined_xyz(self) -> None:
        src = (FIXTURES / "dual_start_end.gcode").read_text(encoding="utf-8").splitlines()
        out, n = xy_then_z_after_purge(src)
        self.assertEqual(n, 1)
        self.assertNotIn("G1 X100 Y100 Z0.3 F900", out)
        xy_i = next(i for i, line in enumerate(out) if "X100" in line and "Y100" in line)
        z_i = next(i for i, line in enumerate(out) if line.startswith("G0 F300 Z"))
        self.assertLess(xy_i, z_i)
        self.assertIn("X100", out[xy_i])
        self.assertIn("Y100", out[xy_i])
        self.assertNotIn("Z", out[xy_i].split(";", 1)[0])
        out2, n2 = xy_then_z_after_purge(out)
        self.assertEqual(n2, 0)

    def test_xy_then_z_leaves_ideamaker_order(self) -> None:
        src = (FIXTURES / "ideamaker_left_start_end.gcode").read_text(encoding="utf-8").splitlines()
        out, n = xy_then_z_after_purge(src)
        self.assertEqual(n, 0)
        self.assertEqual(out, src)

    def test_xy_then_z_on_prusaslicer_reference(self) -> None:
        path = (
            ROOT
            / "reference"
            / "prusaslicer"
            / "Raise3DTest_0.4n_0.2mm_PLA_PRO2PLUS_HS_DUAL_3h2m.gcode"
        )
        src = path.read_text(encoding="utf-8").splitlines()
        out, n = xy_then_z_after_purge(src)
        self.assertEqual(n, 1)
        m1001 = next(i for i, line in enumerate(out) if line.strip() == "M1001")
        xy_i = next(
            i
            for i, line in enumerate(out[m1001:], m1001)
            if line.startswith("G") and "X" in line and "Y" in line and "E" not in line.split(";", 1)[0]
        )
        z_i = next(i for i, line in enumerate(out[m1001:], m1001) if line.startswith("G0 F300 Z"))
        self.assertLess(xy_i, z_i)

    def test_feature_flow_matches_ideamaker_pla_split(self) -> None:
        src = [
            "; generated by PrusaSlicer 2.9.6 on 2026-09-10 at 13:00:00 UTC",
            "M221 T0 S94",
            "T0",
            "G1 F140 E29",
            "M1001",
            ";LAYER:0",
            "G1 X5 Y5 E0.5000",
            ";TYPE:External perimeter",
            "G1 E1.5000 F1500",
            "G1 X10 Y10 E1.0000",
            ";TYPE:Wipe tower",
            "G1 X20 Y20 E2.0000",
            ";LAYER:1",
            ";TYPE:Perimeter",
            "G1 X30 Y30 E1.0000",
            ";TYPE:Top solid infill",
            "G1 X40 Y40 E1.0000",
            "M1002",
        ]
        out, n = apply_ideamaker_feature_flow(src)
        self.assertEqual(n, 3)
        self.assertEqual(out[out.index("M1001") + 1], FEATURE_FLOW_MARKER)
        self.assertIn("G1 X5 Y5 E0.4500", out)
        self.assertIn("G1 E1.5000 F1500", out)
        self.assertIn("G1 X10 Y10 E0.9000", out)
        self.assertIn("G1 X20 Y20 E2.0000", out)
        self.assertIn("G1 X30 Y30 E1.0000", out)
        self.assertIn("G1 X40 Y40 E1.0600", out)
        out2, n2 = apply_ideamaker_feature_flow(out)
        self.assertEqual(n2, 0)
        self.assertEqual(out2, out)

    def test_feature_flow_skips_ideamaker_and_non_pla(self) -> None:
        ideamaker = [
            "M221 T0 S94.00",
            "M1001",
            ";TYPE:WALL-OUTER",
            "G1 X10 Y10 E1.0000",
            "M1002",
        ]
        out, n = apply_ideamaker_feature_flow(ideamaker)
        self.assertEqual(n, 0)
        self.assertEqual(out, ideamaker)

        petg = [
            "; generated by PrusaSlicer 2.9.6 on 2026-09-10 at 13:00:00 UTC",
            "M221 T0 S100",
            "M1001",
            ";TYPE:External perimeter",
            "G1 X10 Y10 E1.0000",
            "M1002",
        ]
        out, n = apply_ideamaker_feature_flow(petg)
        self.assertEqual(n, 0)
        self.assertEqual(out, petg)

    def test_feature_flow_scales_only_the_pla_tool(self) -> None:
        src = [
            "; generated by PrusaSlicer 2.9.6 on 2026-09-10 at 13:00:00 UTC",
            "M221 T0 S94",
            "M221 T1 S100",
            "T0",
            "M1001",
            ";LAYER:0",
            ";TYPE:External perimeter",
            "G1 X10 Y10 E1.0000",
            "T1",
            "G1 X20 Y20 E1.0000",
            "M1002",
        ]
        out, n = apply_ideamaker_feature_flow(src)
        self.assertEqual(n, 1)
        self.assertIn("G1 X10 Y10 E0.9000", out)
        self.assertIn("G1 X20 Y20 E1.0000", out)

    def test_fill_skipped_sequential_object_first_layer(self) -> None:
        lines = [
            "; generated by PrusaSlicer 2.9.6",
            "M1001",
            ";LAYER:0",
            ";Z:0.300",
            "G1 X10 Y10 E1",
            ";LAYER:99",
            ";Z:20.100",
            "G1 X11 Y11 E1",
            "G1 Z20.1",
            "G1 X50 Y50 F9000",
            ";LAYER_CHANGE",
            ";Z:0.3",
            ";HEIGHT:0.3",
            "G1 Z.3",
            ";TYPE:Perimeter",
            "G1 X50 Y50 E1",
            ";LAYER:101",
            ";Z:0.500",
            "G1 X51 Y51 E1",
            "M1002",
        ]
        out, n = fill_skipped_object_first_layers(lines)
        self.assertEqual(n, 1)
        i100 = out.index(";LAYER:100")
        self.assertEqual(out[i100 : i100 + 3], [";LAYER:100", ";Z:0.3", ";HEIGHT:0.3"])
        self.assertLess(i100, out.index("G1 X50 Y50 E1"))
        self.assertLess(out.index("G1 X50 Y50 E1"), out.index(";LAYER:101"))
        out2, n2 = fill_skipped_object_first_layers(out)
        self.assertEqual(n2, 0)

    def test_fill_skipped_sequential_uses_z_drop_without_layer_change(self) -> None:
        lines = [
            "; generated by PrusaSlicer 2.9.6",
            "M1001",
            ";LAYER:0",
            "G1 X10 Y10 E1",
            ";LAYER:99",
            "G1 X11 Y11 E1",
            "G1 Z20.1",
            "G1 X50 Y50 F9000",
            "G1 Z.3",
            ";TYPE:Perimeter",
            "G1 X50 Y50 E1",
            ";LAYER:101",
            "G1 X51 Y51 E1",
            "M1002",
        ]
        out, n = fill_skipped_object_first_layers(lines)
        self.assertEqual(n, 1)
        i_drop = out.index("G1 Z.3")
        self.assertEqual(out[i_drop + 1], ";LAYER:100")
        self.assertEqual(out[i_drop + 2], ";Z:0.300")
        self.assertLess(out.index(";LAYER:100"), out.index("G1 X50 Y50 E1"))

    def test_feature_flow_scales_sequential_object_first_layer(self) -> None:
        src = [
            "; generated by PrusaSlicer 2.9.6 on 2026-09-10 at 13:00:00 UTC",
            "M221 T0 S94",
            "T0",
            "M1001",
            ";LAYER:0",
            ";Z:0.3",
            ";TYPE:External perimeter",
            "G1 X10 Y10 E1.0000",
            ";LAYER:1",
            ";Z:0.5",
            ";TYPE:Perimeter",
            "G1 X11 Y11 E1.0000",
            ";LAYER:99",
            ";Z:20.1",
            "G1 X12 Y12 E1.0000",
            "G1 Z.3",
            ";TYPE:External perimeter",
            "G1 X50 Y50 E1.0000",
            ";LAYER:101",
            ";Z:0.5",
            "G1 X51 Y51 E1.0000",
            "M1002",
        ]
        out, n = apply_ideamaker_feature_flow(src)
        self.assertEqual(n, 2)
        self.assertIn("G1 X10 Y10 E0.9000", out)
        self.assertIn("G1 X11 Y11 E1.0000", out)
        self.assertIn("G1 X12 Y12 E1.0000", out)
        self.assertIn("G1 X50 Y50 E0.9000", out)
        self.assertIn("G1 X51 Y51 E1.0000", out)


if __name__ == "__main__":
    unittest.main()

